UHF-8926
City-of-Helsinki/drupal-helfi-kasvatus-koulutus pull request #460
Opened 2023-10-13 10:30 UTC by rpnykanen

# [UHF-8926](https://helsinkisolutionoffice.atlassian.net/browse/UHF-0000)

-Prevent white screen while editing group menu item translation
-Node's edit pages "published on main navigation" checkbox now updates based on group's menu content item's content translation status

## What was done
Updated group module
Fixed white screen.
Form alter to keep the "content translation status" checkbox on correct state. For group content, the "published in main navigation" state follows the node's published state. Value is updated while saving (not with javascript)
Update hook to update group's menu item's content translation status to match node status.

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-8926`
  * `composer require drupal/helfi_navigation:dev-UHF-8926`
  * `make fresh`
* Run `make drush-cr`

## How to test
Log in as user which is assigned to a group, for example user 19.
- Go to any group, [go to the group's menu](https://helfi-kasko.docker.so/en/childhood-and-education/group/1/menu/1/edit?destination=/fi/kasvatus-ja-koulutus/group/1/menus&group_content_menu_type=kasko_group_menu) and try to translate any menu item. The edit form for menu item should load without crash
- Go to any node which is on the group's menu
  - The "published in main navigation" button should be in correct position when node edit form is loaded (matches menu translation state)
  - Updating node's "published in main navigation" should change the group menu item's translation status.
  - Creating and translating a node and adding it to a group should work normally
- Compare couple of the group menus as incognito user with production menu. It should look the same

* [x] Check that this feature works
* [ ] Check that code follows our standards

## Other PRs:

* https://github.com/City-of-Helsinki/drupal-module-helfi-navigation/pull/47

[UHF-8926]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-10-17 05:02 UTC, tuutti requested changes

2023-10-17 05:02 UTC, tuutti commented on public/modules/custom/helfi_group/helfi_group.module
> +  if (!empty($values['entity_id'])) {
These two ifs can be combined

2023-10-18 07:33 UTC, tuutti approved these changes

2023-10-18 14:20 UTC, teroelonen approved these changes
This is good to go 🦖

2023-10-19 07:24 UTC, merged