UHF-9150: Import more ontology words and display those on comprehensive school TPR unit page
City-of-Helsinki/drupal-helfi-kasvatus-koulutus pull request #479
Opened 2023-11-08 13:31 UTC by Jussiles

# [UHF-9150](https://helsinkisolutionoffice.atlassian.net/browse/UHF-9150)
# [UHF-9157](https://helsinkisolutionoffice.atlassian.net/browse/UHF-9157)

## What was done

* This thing was fixed

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-0000_insert_correct_branch`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2023-11-09 07:26 UTC, tuutti requested changes

2023-11-09 07:26 UTC, tuutti commented on public/modules/custom/helfi_kasko_content/helfi_kasko_content.info.yml
> +  - helfi_tpr:helfi_school_addons
This should be `helfi_school_addons:helfi_school_addons`

2023-11-09 07:26 UTC, tuutti commented on public/modules/custom/helfi_kasko_content/helfi_kasko_content.module
> +function helfi_kasko_content_theme() {
Missing return type

2023-11-09 07:26 UTC, tuutti commented on public/modules/custom/helfi_kasko_content/src/Plugin/Field/FieldFormatter/OntologyWordDetailsFormatter.php
> +        // uses differentUnicode char U+2013 than high school
missing space between different and unicode

2023-11-09 07:26 UTC, tuutti commented on public/modules/custom/helfi_kasko_content/src/UnitOntologyWordDetailsUtility.php
> +  public function findOntologyWordKeysLabelsbyId($id): Array|null {
Array return type should be in lowercase

2023-11-15 20:54 UTC, dire reviewed
Works very nicely! Found only some nitpicks.

2023-11-15 20:54 UTC, dire commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_unit-ontologyword-details.scss
> +    margin-bottom: 8px;
Should some variable be used here instead of pixels? For example `$spacing-half`?

2023-11-15 20:54 UTC, dire commented on public/modules/custom/helfi_kasko_content/src/SchoolUtility.php
> +  }
There are `camelCase` and `snake_case` variables mixed in this file. Probably should stick to one style. I don't know if it matters which one.

2023-11-16 05:53 UTC, dire commented on conf/cmi/core.entity_form_display.tpr_unit.tpr_unit.default.yml
> -  show_www: true
Is this change fine? I don't actually know what this field is or in which instances it's needed.

2023-11-16 05:54 UTC, dire approved these changes

2023-11-16 07:24 UTC, tuutti approved these changes

2023-11-16 09:04 UTC, merged